# Generated by Django 4.2 on 2024-06-14 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tool', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tool',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
